### ISSUE TITLE
Add language header to API calls

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#311]
This will be used by the backend to return localized error messages.

eg. Accept-Language: en-US, fr-CA, es-ES

**Comment by AdamGrzybkowski** [comment]
@hamorillo @maxme 

We have a couple of ways to do that and I would like to get your opinions about it. 

1. Keep `:gravatar` module as simple as possible and don't add more Android dependencies.

This means we would have to ask the third-party dev to pass App/System languages via Gravatar object. The code could look like this:
```
Gravatar.apiKey("key").acceptedLanguages("en-US") //currently we have Gravatar.initialize("key")
```

As mentioned this wouldn't require extra dependency in `:gravatar` module and the third-party dev has full control over languages list.

We could then initialize this in the QuickEditor ourselves (because we need that). 

Two cons I see at least:
- A bit more complicated for third-party devs
- We would override the third-party app setup in the QuickEditor, we can only have one instance per app.

2. Add `core` dependency to the `:gravatar` module and get the languages.

We need that dependency to use the [LocaleManagerCompat](https://developer.android.com/reference/androidx/core/app/LocaleManagerCompat). Once we have this (and the application context) we can get the list simply with this code:
```
private val Context.acceptedLanguages: String
    get() = LocaleManagerCompat.getApplicationLocales(this).toLanguageTags().ifEmpty {
        LocaleManagerCompat.getSystemLocales(this).toLanguageTags()
    }
```
First, we try to read the app languages and if empty we get the system ones.

This solution makes the integration easier for third-party devs, but the drawbacks are: 
- Languages are not customizable - no way to pass other than those retrievies via `LocaleManagerCompat` (Although, this might be a pro here, as it eliminates the problem with overridden config mentioned above)
- `:gravatar` module has an extra Android dependency


WDYT?

**Comment by hamorillo** [comment]
1. In this option, we need to consider that the language can be switched for that concrete app during its execution. We'll need to provide an API not just for the initialization but also to allow the third party to switch the preferred order.

2. I'm a bit concernt about adding the depency. We can introduce some conflicts between versions in the third-party apps. However, we've already added in `:ui` or `QE` modules.

💡❓ _What about a variation of option 1?_
Instead of passing the acceptedLanguages directly, we can define and interface that the thrid-party can implement in order to provide us with that info. They'll pass an implementation of that interface and we can request the accepted languagues in every request just in case those preferences have changed between requests.

```kotlin
public interface GravatarLanguageProvider {
    public fun getAcceptedLanguages(): String
}
```

```kotlin
val languageProvider = object : GravatarLanguageProvider {
    override fun getAcceptedLanguages(): String {
        return ...
    }
}

Gravatar.apiKey("key").languageProvider(languageProvider)
```

The implementation of the `languageProvider` would depend only on the third-party app but we can suggest something like what you've mentioned and explain that this is only needed for the error localization. If they are going to use their own error handling they don't need to provide it.

**Comment by AdamGrzybkowski** [comment]
>we need to consider that the language can be switched for that concrete app during its execution

Yes! This is indeed a problem and could be solved with your suggested solution. 

It still has all the drawbacks mentioned above, and it's even more complicated. The alternative is doing it all for the third-party dev with one extra dependency and no need for providers. 🤔

**Comment by hamorillo** [comment]
The question is if, as a third-party developer, I would directly show an error received from a service. In general, I would say the answer is no. I'll probably ask for a list of error codes and map those that I think are important in my case. So the most common use (_obviously this is totally subjective and I may be wrong_) is that developers don't really care about the localization of the error messages. Based on that, I doubt if adding the extra dependency is worth it or if it can create more problems than benefits.

On the other hand, if I'm not wrong we want to use those localized errors in QE so it's a point to go with 2. However, If we decide to go with option 1, we can provide by default the languages (since QE can get then) and let the developer override that config. 

I'm not completely against adding the dependency; I'm just trying to think through it twice to see if it's our best option in the current situation.
